name: Frontend push
on:
  - push
defaults:
  run:
    working-directory: ./frontend
jobs:
  build_and_deploy_frontend:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "skull-web"
    steps:
      - name: Checkout on branch
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Lint and build project
        run: |
          cd frontend
          npm run lint
          npm run build

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./frontend/Dockerfile

      - name: Build project image
        run: docker image build --tag="${IMAGE_NAME}" ./

      - name: Login to Docker Hub
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          username: loancb
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push release image to docker hub
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./frontend
          tags: "loancb/skull-web:${{ github.ref_name }}"

      - name: Push unstable release to docker hub
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./frontend
          tags: "loancb/skull-web:unstable"
